easy_admin:
    # ...
    entities:
        # ...
        Report:
            class: App\Entity\Report
            label: Reportes
            # ...
            list:
                # ...
                - { label: 'Generar informe', route: 'admin_report', icon: 'file-pdf' }